services:
  - type: web
    name: smartcam-shield
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
